# Gitpod configuration file

image: gitpod/workspace-python

tasks:
  - init: |
      echo "Setting up Python environment..."
      sudo apt-get update
      sudo apt-get install -y graphviz
      pip install pandas
      pip install -r requirements.txt
    command: |
      echo "Ready to code!"
      python main.py -i ./examples/testinput.py
      python -m http.server 8080 --directory . &
      gp preview $(gp url 8080)/cells_output.html

ports:
  - port: 8080
    onOpen: ignore
